name: 'PR Title Checker'
on: 
  pull_request:
    types: [edited, opened, synchronize, reopened]

jobs:
  title-check:
    runs-on: ubuntu-latest
    steps:
      - uses: huytq-0932/action-pr-title@master
        with:
          regex: '^(refs|Refs)[ ]*\[(TASK|BUG|FEATURE|TEST|SUPPORT)*\]\[[0-9]*\][ ]*:[ ]*' # Regex the title should match.
